nipad/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path(r'^adminanipad/', admin.site.urls),
    re_path(r'^', include('nipadapp.urls')),
] 

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nipadapp/urls.py
from django.urls import path, re_path

from .import views
from .views import CutomerNumJsonView

app_name = 'nipadapp'

urlpatterns = [
    re_path(r'^$', views.home, name='home'),

    re_path(r'^propos/', views.propos, name='propos'),
    re_path(r'^regions/', views.regions, name='regions'),
    re_path(r'^program/', views.program, name='program'),
    re_path(r'^rejoindre/', views.rejoindre, name='rejoindre'),
    re_path(r'^contactes/', views.contactes, name='contactes'),
    re_path(r'^services/', views.services, name='services'),
    path('customers-json/', CutomerNumJsonView.as_view(), name='customers-json'),

]

nipadapp/models.py
from django.db import models
import datetime
from django.db.models.fields import BooleanField
from django.template.defaultfilters import slugify # for auto-slug _  #pip install python-slugify



# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=101)
    slug = models.SlugField(max_length=150, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    photo = models.ImageField(upload_to='%Y/%m/%d/', default='default.png', blank=True)
    # title slug date body thumb

    def __str__(self):
        return self.title
    
    def save(self): # for auto-slug __   date and title
        super(Article, self).save()
        date = datetime.datetime.now()
        self.slug = '%i-%i-%i-%s-%s-%s-%s' % (
            date.year, date.month, date.day, date.hour, date.minute, date.second, slugify(self.title)
        )
        super(Article, self).save()

    def snippet(self):
        return self.body[:100] +'...'

class Customer(models.Model):
    name = models.CharField(max_length=80)
    active = BooleanField(default=True)

    def __str__(self):
        return str(self.name)

        ##

nipadapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, View
from .models import*
from django.http import JsonResponse

# Create your views here.

def home(request):
    #upcomingEvents = Event.objects.all().filter(expired = False).order_by('expiration_date')
     #upcoming variable receives data from db witch is not expired
    return render(request, 'nipadapp/home.html')

def propos(request):
    return render(request, 'nipadapp/propos.html')

def regions(request):
    return render(request, 'nipadapp/regions.html')

def program(request):
    return render(request, 'nipadapp/program.html')

def rejoindre(request):
    return render(request, 'nipadapp/rejoindre.html')

def contactes(request):
    return render(request, 'nipadapp/contactes.html')

def services(request):
    return render(request, 'nipadapp/services.html')

class CutomerNumJsonView(View):
    def get(self, *args, **kwargs):
        customer_count = Customer.objects.filter(active=True).count()
        return JsonResponse({'customer_count':customer_count})

nipadapp/templates/nipadapp/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="css/bootstrap-responsive.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>NIPAD</title>
</head>

<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-success fixed-top " id="bg-menu">
        <div class="container-lg">
        <a class="navbar-brand" href="#">
            <img src="{% static 'logo.png' %}" alt="NIPAD" width="50px" height="50px">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ms-auto mb-2 mb-md-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'nipadapp:home' %}">Acceuil</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'nipadapp:propos' %}">A Propos</a>
            </li>

            <li class="nav-item">
                <a class="nav-link active" href="{% url 'nipadapp:services' %}">Nos Services</a>
            </li>
    
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'nipadapp:regions' %}">Regions</a>
            </li>
    
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'nipadapp:program' %}">Projets/Programmes</a>
            </li>

            <li class="nav-item">
                <a class="nav-link active" href="{% url 'nipadapp:rejoindre' %}">Nous Rejoindre</a>
            </li>

            <li class="nav-item">
                <a class="nav-link active" href="{% url 'nipadapp:contactes' %}">Contactes</a>
            </li>
    
            </ul>
        </div>
        </div>
    </nav>
    </header>

  


<body>

    {% block content%}

    {% endblock %}
      


    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!--jquery and js of counter up _ ex:count projects-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script>

    <script>
        //counta = variable from html
        //countUp = function for counting when you scroll down/up the webpage
        $('.counta').counterUp({
            delay: 10,
            time: 2500
        });
        
        //counter=variable from html
        $('.counter').counterUp({
            delay: 10,
            time: 2500
        });

    </script>

</body>


<!-- Footer -->

nipadapp/templates/nipadapp/contactes.html
{% extends 'nipadapp/base_layout.html' %} <!--namspace of templates-->
{% load static %}

{% block content %}
<br>
<br>

<br>
<br>
<h1>helloooooooo contacts</h1>

{% endblock %}

nipadapp/templates/nipadapp/home.html
{% extends 'nipadapp/base_layout.html' %} <!--namspace of templates-->
{% load static %}

{% block content %}
<br>
<br>
<br>
    <img src="{% static 'flock21a.jpg' %}" class="w-100" style="" alt="Little nipadapp Burundi">
    <div class="card ">
        
        <img src="{% static 'flock21a.jpg' %}" class="" style="" alt="Little nipadapp Burundi">
        <div class="card shadow text-white" style="background: black;
        overflow: hidden;" >
    
            <img src="{% static 'default.png' %}" class="" style="object-fit: cover;
            opacity: 0.4;" alt="Little nipadapp Burundi">

            <div class="overlay-content align-items-end text-white">

                <div class="col-md-3 text-center my-auto">
                    <div class="card-img-overlay card-body align-items-center col-md d-flex justify-content-center">

                        <div class="inner">
                            <div class="card-body" id="zoomText">
                                <h1 class="card-title" data-mdb-animation="zoom-in" >NIPAD</h1>
                                <br>
                                <h4 class="card-text">Catalyser les opportunités d'investissement en Afrique</h4>
                                <br>
                                <a href="{% url 'nipadapp:services' %}" class="btn btn-success">Nos Services</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
                    <br>
                    <br>

    <!-- =============ABOUT US===============-->
 {% comment %} <div class="container marketing"> {% endcomment %}
<div class="container">
    <div class="row shadow m-6 justify-content-center">
        <div class="col-md-6 p-5">
            <h2 class="cardNziza-title" >A Propos</h2>
            <br>
            <P class="text-center">Nous sommes une Equipe de professionnels preoccupés par le Développement du Continent Africain: "

                Nous croyons que l'Afrique a des potentielités pour sa prosperité et il faut que toute  Institution publique ou para Etatique, tout acteur ou partenaire de développement, tout investisseur portent  en main une clé."
            </p>
            <br>
            <div class="text-center">
                <a href="{% url 'nipadapp:propos' %}" style="color:white;" class="btn btn-success" >Lire plus</a>
            </div>
        </div>
        <div class="col-md-6 ">
            <div class="inner">
                <img src="{% static 'default.png' %}" class="w-100" style="max-width: 100%; height: auto;" alt="">
            </div>
        </div>
    </div>

        <!-- ===============End About Us=========-->
        <br>
        <br>
        <br>
    <!-- =============Video presentation===============-->

    
    <div class="row shadow m-6 justify-content-center">
        <div class="col-md-6 ">
            <div class="inner">
                <img src="{% static 'default.png' %}" class="w-100" style="max-width: 100%; height: auto;" alt="">
            </div>
        </div>

        <div class="col-md-6 p-5">
            <h2 class="cardNziza-title" class="fw-bold fs-1">Presentation</h2>
            <br>
            <P class="text-center">We are a covenanted spiritual family that desires and pursues a Trinitarian fullness , for a lasting impact to the glory of God, our joy in Jesus Christ.

                Trinitarian fullness: <br>
                - Rooted in the Word of Christ<br>
                - Filled with the Power of the Holy Spirit <br>
                - Ablaze with love for the Father</P>
                
        </div>
        
    </div>

        <!-- ===============end Video presentation=========-->


    <br>
    <br>
    <br>


        <!-- ===========================-->
    <div class="row justify-content-center">
        <h2 class="cardNziza-title" class="text-center ">Special title treatment</h2>
        <p class="text-center">With supporting text below as a natural lead-in to additional content, With supporting text below as a natural lead-in to additional content, With supporting text below as a natural lead-in to additional content.</p>
    </div>
        <br>
    <div class="row">
        <div class="col-md-4">
            <div class="image"> <img src="https://images.pexels.com/photos/1371360/pexels-photo-1371360.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="">
                <div class="overlay">
                    <p class="amount">$399</p>
                    <p class="h4">Group Tour in Maldives</p>
                    <p class="textmuted">Ameeru Ahmed magu male,female</p>
                    <ul class="list-unstyled d-flex ">
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star-half-alt"><span class="ms-2 review">500 reviews</span> </span></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="image"> <img src="{% static 'default.png' %}" alt="">
                <div class="overlay">
                    <p class="amount">$399</p>
                    <p class="h4">Group Tour in Maldives</p>
                    <p class="textmuted">Ameeru Ahmed magu male,female</p>
                    <ul class="list-unstyled d-flex ">
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star-half-alt"><span class="ms-2 review">500 reviews</span> </span></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="image"> <img src="https://images.pexels.com/photos/4388165/pexels-photo-4388165.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="">
                <div class="overlay">
                    <p class="amount">$399</p>
                    <p class="h4">Group Tour in Maldives</p>
                    <p class="textmuted">Ameeru Ahmed magu male,female</p>
                    <ul class="list-unstyled d-flex ">
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star"></span></li>
                        <li><span class="fas fa-star-half-alt"><span class="ms-2 review">500 reviews</span> </span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- ===============end =========-->
    <br>
    <br>
    <br>

    <!-- ===========================-->
    <div class="row justify-content-center">
        <h2 class="cardNziza-title" class="text-center ">Special title treatment</h2>
        <p class="text-center">With supporting text below as a natural lead-in to additional content, With supporting text below as a natural lead-in to additional content, With supporting text below as a natural lead-in to additional content.</p>
    </div>

    <br>
    <div class="row justify-content-center">

        <div class="col-md-4">
            
            <div class="cardNziza">
                <div class="cardNziza-image">
                    <img src="{% static 'flock21a.jpg' %}" alt="Orange" />
                </div>
                
                <div class="cardNziza-body">
                
                <div class="cardNziza-date">
                    <time>20 Novembre 1992</time>
                </div>
                
                <div class="cardNziza-title">
                    <h3>Lorem Ipsum</h3>
                </div>
                
                <div class="cardNziza-excerpt">
                    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam voluptatibus autem consectetur voluptate facere at, omnis ab optio placeat officiis! Animi modi harum enim quia veniam consectetur unde autem inventore.</p>
                </div>
                
                </div>
            </div>
        </div>

        <div class="col-md-4">
            
            <div class="cardNziza">
                <div class="cardNziza-image">
                    <img src="{% static 'flock21a.jpg' %}" alt="Orange" />
                </div>
                
                <div class="cardNziza-body">
                
                <div class="cardNziza-date">
                    <time>20 Novembre 1992</time>
                </div>
                
                <div class="cardNziza-title">
                    <h3>Lorem Ipsum</h3>
                </div>
                
                <div class="cardNziza-excerpt">
                    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam voluptatibus autem consectetur voluptate facere at, omnis ab optio placeat officiis! Animi modi harum enim quia veniam consectetur unde autem inventore.</p>
                </div>
                
                </div>
            </div>
        </div>

        <div class="col-md-4">
            
            <div class="cardNziza">
                <div class="cardNziza-image">
                    <img src="{% static 'flock21a.jpg' %}" alt="Orange" />
                </div>
                
                <div class="cardNziza-body">
                
                <div class="cardNziza-date">
                    <time>20 Novembre 1992</time>
                </div>
                
                <div class="cardNziza-title">
                    <h3>Lorem Ipsum</h3>
                </div>
                
                <div class="cardNziza-excerpt">
                    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam voluptatibus autem consectetur voluptate facere at, omnis ab optio placeat officiis! Animi modi harum enim quia veniam consectetur unde autem inventore.</p>
                </div>
                
                </div>
            </div>
        </div>

    </div>
    <!-- ===============end=========-->
        
        <br>
        <br>
        <br>

        <!-- ===============PROJECTS counter=========-->
    <div class="row justify-content-md-center">
        
        <div class="col-md-4 d-flex justify-content-center text-center">
            
            <div class="card shadow border-success mb-3" style="width: 18rem; ">
                
                <div class="card-body text-center">
                    <h4 class="card-title">Projets soutenus</h4> 
                    <p class="card-text ">
                        <h1 class="counta" style="color:green;" >5</h1>
                    </p>
                </div>

            </div>
            <br>
        </div>

        <div class="col-md-4 d-flex justify-content-center text-center">
            
            <div class="card shadow border-danger mb-3" style="width: 18rem; ">
                
                <div class="card-body text-center">
                    <h4 class="card-title">Projets encours</h4> 
                    <p class="card-text ">
                        <h1 class="counter" style="color:red;">100</h1>
                    </p>
                </div>

            </div>
            <br>
        </div>

    </div>
    <!-- ===============end PROJECTS counter=========-->
 

<br>
<br>
<br>
<br>
<br>


{% endblock %}

nipadapp/templates/nipadapp/program.html
{% extends 'nipadapp/base_layout.html' %} <!--namspace of templates-->
{% load static %}

{% block content %}
<br>
<br>

<br>
<br>
<h1>helloooooooo program</h1>

{% endblock %}

nipadapp/templates/nipadapp/propos.html
{% extends 'nipadapp/base_layout.html' %} <!--namspace of templates-->
{% load static %}

{% block content %}
<br>
<br>

<br>
<br>
<div class="container">
    <!-- =============ABOUT US===============-->
 {% comment %} <div class="container marketing"> {% endcomment %}
    
        <div class="row shadow m-6 justify-content-center">
            <div class="col-md-6 ">
                <div class="inner">
                    <img src="{% static 'default.png' %}" class="w-100" style="max-width: 100%; height: auto;" alt="">
                </div>
            </div>

            <div class="col-md-6 p-5">
                <h2 class="cardNziza-title" >A Propos</h2>
                <br>
                <P class="text-center">Nous sommes une Equipe de professionnels preoccupés par le Développement du Continent Africain: "

                    Nous croyons que l'Afrique a des potentielités pour sa prosperité et il faut que toute  Institution publique ou para Etatique, tout acteur ou partenaire de développement, tout investisseur portent  en main une clé."
                </p>
                    
            </div>
            
        </div>
    
<br>
<br>
    
        <div class="card shadow">
            <div class="card-header">
                <h3 class="cardNziza-title">Historique et raison d'être</h3>
            </div>
            <div class="card-body">
            <p class="text-center">
                Tout commence par une prise de contact continuelle,
                L'Afrique contient plus d'opportunités non exploitées suffisamment par son peuple pour cause de plusieurs raisons liées au manque d'esprit collaboratif plus serieux entre le secteur public et privé.
                L'ecosystème des affaires en Afrique reste au rythme le plus bas comparé aux autres continents du Nord car il y a manque d'echange d'opportunités, de connaissances et la collaboration à valeur mutuelle entre acteurs et autres.
                <br>
                <br>
                Les entrepreneurs que les Investisseurs ont pas mal de blockages sur le territoire et liés au Contexte des sytèmes locaux.
                Quelques pays ont fait un pas en avant alors que les autres sont toujours en arrière et continuent à s'appauvrir d'avantage. Ces disparités auraient été eliminées si tout acteur de développement et Investisseurs envisageant contribuer sur l'econonomie du Continent collaborent et renforcent de relations de convergence sur la diversification des opportunités d'investissement pour l'inclusion financière sur tout le Continent.
                <br>
                <br>
                NIPAD a pris naissance via les deux jeunes entrepreneurs Burundais(Mr Antoine NIRAGIRA et Mr Roger Milla NSHIMIRIMANA) qui se sont rencontrés et dans leur discussion, ils sont tous revenus sur le fait que il n'y a pas d'un Cadre ou organe commun qui donne des conseils, incite et  centralise les opportunités d'investissement sur le Continent Africain.
                Ils ont tous  rapidement epousé l'idée et ont rejoint d'autres personnes d'importance dans le developpement durable pour partager la mission et la vision.
            </p>
            </div>
        </div>
    
        <!-- ===============End About Us=========-->

        <br>
        <br>
        <br>

        <!-- ===============Mission Vision Objectis=========-->
 
        
        <div class="row justify-content-md-center">
            
            <div class="col-md-4 d-flex justify-content-center text-center">
                
                <div class="card shadow border-success mb-3" style="width: 18rem; ">
                    
                    <div class="card-body text-center">
                        <h1 class="card-title">Mission</h1> 
                        <p class="card-text ">Proclaim the Kingdom that has come through death and resurrection of Jesus Christ. Proclaim the Kingdom that has come through death and resurrection of Jesus Christ</p>
                    </div>

                </div>
                <br>
            </div>

            <div class="col-md-4 d-flex justify-content-center text-center">
               
                <div class="card shadow border-danger mb-3" style="width: 18rem; ">
                    
                    <div class="card-body text-center">
                        <h1 class="card-title">Vision</h1> 
                        <p class="card-text">Proclaim the Kingdom that has come through death and resurrection of Jesus Christ. Proclaim the Kingdom that has come through death and resurrection of Jesus Christ</p>
                    </div>

                </div>
                <br>
            </div>

            <div class="col-md-4 d-flex justify-content-center text-center">
                
                <div class="card shadow border-warning mb-3" style="width: 18rem; ">
                    
                    <div class="card-body text-center">
                        <h1 class="card-title">Objectis</h1> 
                        <p class="card-text">Proclaim the Kingdom that has come through death and resurrection of Jesus Christ. Proclaim the Kingdom that has come through death and resurrection of Jesus Christ</p>
                    </div>

                </div>
                <br>
            </div>  
        </div>
       
        <!-- ===============Mission Vision Objectis=========-->
</div>
{% endblock %}

nipadapp/templates/nipadapp/regions.html
{% extends 'nipadapp/base_layout.html' %} <!--namspace of templates-->
{% load static %}

{% block content %}
<br>
<br>

<br>
<br>
<h1>helloooooooo region</h1>

{% endblock %}

nipadapp/templates/nipadapp/rejoindre.html
{% extends 'nipadapp/base_layout.html' %} <!--namspace of templates-->
{% load static %}

{% block content %}
<br>
<br>

<br>
<br>
<h1>helloooooooo rejoindre</h1>

{% endblock %}